export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const ADD_TASK = 'ADD_TASK';
export const PERSIST_SECONDS = 'PERSIST_SECONDS'
export const REMOVE_CURRENT_TIMER ='REMOVE_CURRENT_TIMER'
export const MARK_AS_COMPLETE = 'MARK_AS_COMPLETE';
export const DELETE_POMODORO = 'DELETE_POMODORO';