export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const UPDATE_TASK_NAME = 'UPDATE_TASK_NAME';
export const ADD_TASK = 'ADD_TASK';
export const TOGGLE_TIMER = 'TOGGLE_TIMER';
export const CHANGE_POMODORO_TYPE = 'CHANGE_POMODORO_TYPE';